sonata_admin:
  dashboard:
    blocks:
      -
        position: left
        type: sonata.admin.block.admin_list

      -
        position: right
        type: sonata.block.service.text
        settings:
          content: >
            <h2>User Count</h2>
      -
        position: right
        type: sonata.block.service.rss
        roles: [POST_READER]
        settings:
          title: Sonata Project's Feeds
          url: https://sonata-project.org/blog/archive.rss